development:
  adapter: mysql2
  encoding: utf8
  database: instabug
  pool: 5
  username: root
  password: mypassword
  host: db
  test:
    adapter: mysql2
    encoding: utf8
    database: instabug
    pool: 30
    username: root
    password: mypassword
    host: db