version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
  web:
    build: .
    command: puma
    ports:
      - "9292:9292"
    links:
      - db
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - '.:/data/redis'
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'